name: knuxt-poc
proxy:
  nginx:
    - knuxt-poc.lndo.site
services:
  cli:
    type: node:6
    build:
      - npm install
      - npm run generate
  appserver:
    type: php:7.1
    via: nginx
    webroot: dist

tooling:
  nuxt:
    cmd: /app/node_modules/.bin/nuxt
    service: cli
  npm:
    service: cli
  grunt:
    cmd: /app/node_modules/.bin/grunt
    service: cli
